freeze_lidar_components: true
freeze_camera_components: true
gt_paste_stop_epoch: -1

data:
  samples_per_gpu: 2
  workers_per_gpu: 4

max_epochs: 6

with_mask: true
# transform_input: 266


# MVP related
dbinfos_file: nuscenes_dbinfos_virtual.pkl
train_pkl: nuscenes_infos_train.pkl
val_pkl: nuscenes_infos_val.pkl

load_augmented: mvp
load_dim: 18
use_dim: 18

model:
  type: BEVFusion
  virtual: True
  with_mask: ${with_mask}
  filter: True
  encoders:
    lidar:
      backbone:
        type: SparseEncoder
        in_channels: ${use_dim}
  fuser:
    type: ConvFuser
    in_channels: [80, 256]
    out_channels: 256

optimizer:
  type: AdamW
  lr: 2.0e-4
  betas: [0.9, 0.999]
  weight_decay: 0.05
  paramwise_cfg:
    custom_keys:
      absolute_pos_embed:
        decay_mult: 0
      relative_position_bias_table:
        decay_mult: 0
      norm:
        decay_mult: 0

lr_config:
  policy: step
  step: [4, 5]