model:
  type: BEVAttn
  encoders:
    camera:
      vtransform:
        type: DepthAttnTransform
        in_channels: 256
        out_channels: 256
        feature_size: ${[image_size[0] // 8, image_size[1] // 8]}
        xbound: [-51.2, 51.2, 0.4]
        ybound: [-51.2, 51.2, 0.4]
        zbound: [-10.0, 10.0, 20.0]
        dbound: [1.0, 60.0, 0.5]
        depth_attn_layers: 1
        depth_attn_cfg:
          type: DepthAttnLayer
          embed_dim: 256
          num_heads: 8
          depth_attn: true
          sem_attn: false
          ffn_cfgs:
            type: FFN
            embed_dims: 256
            feedforward_channels: 512
            num_fcs: 2
            ffn_drop: 0.1
            act_cfg:
              type: ReLU
              inplace: true
          norm_cfg:
            type: LN
        positional_encoding:
          type: LearnedDepthPositionalEncoding
          input_channel: 1
          num_feats: 256
        # positional_encoding_key:
        #     type: SinePositionalEncoding
        #     num_feats: 128
        #     normalize: True
        downsample: 2
        with_bev_embedding: True
        loss_depth_weight: 3.0
  decoder:
    backbone:
      in_channels: 256


