model:
  type: BEVAttnV2
  mult_feat: false
  encoders:
    camera:
      backbone: null
      neck: null
      backbone:
        type: ResNet
        depth: 101
        num_stages: 4
        out_indices: [3]
        frozen_stages: 1
        norm_cfg:
          type: BN2d
          requires_grad: false
        norm_eval: true
        style: 'caffe'
        with_cp: true
        dcn: 
          type: DCNv2
          deform_groups: 1
          fallback_on_stride: false
        stage_with_dcn: [false, false, true, true]
      neck:
        type: FPN
        in_channels: [2048]
        out_channels: 256
        start_level: 0
        add_extra_convs: 'on_output'
        num_outs: 1
        relu_before_extra_convs: true
      vtransform:
        type: DepthAttnTransform
        in_channels: 256
        out_channels: 256
        feature_size: ${[image_size[0] // 4, image_size[1] // 4]}
        xbound: [-51.2, 51.2, 0.4]
        ybound: [-51.2, 51.2, 0.4]
        zbound: [-10.0, 10.0, 20.0]
        dbound: [1.0, 60.0, 0.5]
        depth_attn_layers: 1
        depth_attn_cfg:
          type: DepthAttnLayer
          embed_dim: 256
          num_heads: 8
          ffn_cfgs:
            type: FFN
            embed_dims: 256
            feedforward_channels: 512
            num_fcs: 2
            ffn_drop: 0.1
            act_cfg:
              type: ReLU
              inplace: true
          norm_cfg:
            type: LN
        downsample: 2
        img_downsample_factor: [1, 2, 4]
        # positional_encoding:
        #   input_channel: 1
        #   num_feats: 256
        #   type: LearnedDepthPositionalEncoding
  decoder:
    backbone:
      in_channels: 256

data:
  samples_per_gpu: 4
  workers_per_gpu: 4

optimizer:
  type: AdamW
  lr: 5.0e-5

